name: Fork Sync

permissions:
  contents: write      # 推送代码需要
  workflows: write     # 更新 workflow 文件需要

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Force Sync Upstream
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git remote add upstream https://github.com/huangxd-/danmu_api.git

          git fetch upstream

          git checkout main

          git reset --hard upstream/main

          git push origin main --force

      - name: Done
        run: echo "Fork synced successfully"
